/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    saySomething
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Main_saySomething
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
